module.exports = {
  GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID,
  GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET,
  MONGODB_PASSWORD: process.env.MONGODB_PASSWORD,
  COOKIE_KEY: process.env.COOKIE_KEY,
};
